### PR TITLE
Update PT-BR translation

### PR DESCRIPTION
**Pull request by strund3r**

### CODE REVIEW

**Comment by levoniust** [comment]
Is there a way you can add flashlight support to the app?

**Comment by ztc1997** [comment]
@user226688 fixed 556dc40

**Comment by user226688** [comment]
still get a similar error:

Error:Could not find com.android.tools.build:gradle:3.0.1.
Searched in the following locations:
    file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.pom
    file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.jar
    https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.pom
    https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.jar
Required by:
    project :

**Comment by ztc1997** [comment]
@user226688 update your SDK and AS, and try again.

**Comment by user226688** [comment]
thank you for the reply.
well, I am on Android Studio version 2.3.3 and API level 25.
Do you think I really need to update, I heard there are some problems with Android Studio version 3.

**Comment by ztc1997** [comment]
@user226688 yes, or you can try to change the version of "com.android.tools.build:gradle"

**Comment by user226688** [comment]
As you might have seen I am new to android studio, I'm afraid I don't know how to change the version of "com.android.tools.build:gradle".
If you could help me with a step by step guidance I would be so thankful. 
Thank you very much for your time and effort!

**Pull request merged**
