### PR TITLE
Create values-tr

### PR DESCRIPTION
**Pull request by ghost**
turkish translation

### CODE REVIEW

**Comment by ztc1997** [comment]
Incorrect way to add, I have manually merged.

**Comment by FatihFIRINCI** [comment]
I'm sorry to fault.

**Comment by ztc1997** [comment]
Do not mind, I hope we continue to cooperate in the future.

**Comment by FatihFIRINCI** [comment]
Of course we will continue. Thanks

**Comment by mojaninjaxddd** [comment]
. D

**Pull request closed without merging**
